# Generated by Django 5.1 on 2024-09-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeraccount',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
